language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - secure: Ck4YRyeroQhNFEUe2UOs0xtvsgXlqHFUtJCvHV8doXowXHp9aHRJqQZRJyPrDLERxqzWr6q4L1NIJnjOKALiKN0UrmoVOhRrbblu3FS1W9RmjLVkzohsgzA+zp2C1PdrYwSMS8FFp1SmXORYCB1E2VMNdoBhfKZjAWwLobrxUiU=
    - secure: h0vO8a9n55lXgKTIRFb2WFWpIAzgLfV9OLUaTynbTZBROAzK1M6D2uxA9hnE7tSaxn8jp8Hg7LeyPctn8GRubFMU+P5HxeOhNfkXz8GNv1bUUbwULCt15mTG9ioksvWqg2hTWf4OTGpTiTttPzgIrM/F2/daD/lMhKwHjaJ9YUg=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.2
    env:
    - PYVER=3
  - python: 3.3
    env:
    - PYVER=3
virtualenv:
  system_site_packages: true
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libatlas-dev libatlas-base-dev liblapack-dev python$PYVER-numpy
- sudo apt-get install -qq --force-yes libhdf5-serial-dev libvl-dev texlive-latex-base texlive-latex-extra texlive-math-extra texlive-latex-recommended texlive-fonts-recommended
- pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel sphinx matplotlib nose==1.3.0 jinja2==2.6 cpp-coveralls pygments==1.6
install:
- python bootstrap-buildout.py
- CFLAGS=-coverage ./bin/buildout
script:
- ./bin/python -c 'from bob.ip.base import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ip.base ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*"
- ./src/bob.extension/scripts/upload-sphinx.sh
